### ISSUE TITLE
Ошибка "Слишком длинное имя файла"

### ISSUE THREAD

**Issue by ingver** [theasder/access_books#11]
```
$ python3 script_py3.py
...
downloads/Java/Эванс Б., Вербург М. "Java. Новое поколение разработки" (2014, PDF)/preview.jpg was downloaded.
File downloads/Java/Эванс Б., Вербург М. "Java. Новое поколение разработки" (2014, PDF)/Эванс_Б___Вербург_М____Java__Новое_поколение_ра__.pdf already exists, skipping.
Traceback (most recent call last):
  File "script_py3.py", line 176, in <module>
    download_books()
  File "script_py3.py", line 168, in download_books
    os.mkdir(folder_path)
OSError: [Errno 36] File name too long: 'downloads/Другое/Джез Хамбл, Дэвид Фарли "Непрерывное развертывание ПО. Автоматизация процессов сборки, тестирования и внедрения новых версий программ (2011, PDF)'
```
Запускал под Linux

**Comment by ingver** [comment]
Только что увидел, что #10 про то же
